---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./config/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: localhost:3000,dash.home
    networks:
      - homepage_net

networks:
  homepage_net:
    name: homepage_net

volumes:
  config:
