- name: Configure root dir
  file:
    path: /opt/monitoring
    state: directory
    mode: '0755'

- name: Configur Prometheus dir
  file:
    path: /opt/monitoring/prometheus
    state: directory
    mode: '0755'

- name: Copy docker-compose
  copy:
    src: docker-compose.yml
    dest: /opt/monitoring/docker-compose.yml

- name: Copy Prometheus config
  copy:
    src: prometheus.yml
    dest: /opt/monitoring/prometheus/prometheus.yml
    mode: '0644'

- name: Start monitoring stack
  ansible.builtin.command: docker compose up -d
  args:
    chdir: /opt/monitoring
