---
- name: Configure dir
  ansible.builtin.file:
    path: /opt/adguard
    state: directory
    mode: "0755"

- name: Copy docker-compose
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/adguard/docker-compose.yml

- name: Run adguard
  ansible.builtin.command: docker compose up -d
  args:
    chdir: /opt/adguard
