# Try to ping router every 5 mins to ensure we remain online
watchdog-device = /dev/watchdog
interval        = 25 # Run loop every 5 mins

ping            = 192.168.1.1 # local router

realtime        = yes
priority        = 1

reboot          = yes
