services:
  adguard_home:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    networks:
      - adguard_net
    volumes:
      - config:/opt/adguardhome/conf 
      - work:/opt/adguardhome/work 
    ports:
      - 53:53/udp
      - 53:53/tcp

networks:
  adguard_net:
    driver: bridge
    name: adguard_net

volumes:
  config:
    driver: local
  work:
    driver: local

