- name: Setup Docker (Compose)
  hosts: rpi
  become: true
  roles:
    - role: external/geerlingguy.docker
      vars:
        docker_install_compose_plugin: true
        docker_compose_package: docker-compose-plugin
        docker_compose_package_state: present

- name: Configure watchdog
  hosts: rpi
  become: true
  roles:
    - watchdog

- name: Install GitHub Actions Runner
  hosts: rpi
  become: true
  vars_files:
    - ../vault.yml
  vars:
    github_account: cglavin50
    github_repo: homelab
    access_token: "{{ GITHUB_RUNNER_TOKEN }}"
  roles:
    - monolithprojects.github_actions_runner
