name: Deploy to RPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv (to run ansible)
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -r pyproject.toml

      - name: Run Ansible Playbook
        run: |
          source .venv/bin/activate
          make deploy MODE=local
